In [1]:
import pandas as pd

In [2]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [3]:
df_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
df_train.columns[df_train.isnull().any()]

Index(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence',
       'MiscFeature'],
      dtype='object')

In [6]:
df_train = df_train.drop(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence',
       'MiscFeature'],axis=1)

In [7]:
df_test.columns[df_test.isnull().any()]

Index(['MSZoning', 'LotFrontage', 'Alley', 'Utilities', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath',
       'BsmtHalfBath', 'KitchenQual', 'Functional', 'FireplaceQu',
       'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea',
       'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType'],
      dtype='object')

In [9]:
df_test = df_test.drop(['MSZoning', 'LotFrontage', 'Alley', 'Utilities', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath',
       'BsmtHalfBath', 'KitchenQual', 'Functional', 'FireplaceQu',
       'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea',
       'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType'],axis = 1)

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_train_encoded = df_train.apply(le.fit_transform)

In [13]:
df_test_encoded = df_test.apply(le.fit_transform)

In [19]:
x_train = df_train_encoded.drop(['SalePrice'],axis=1)

In [20]:
y_train = df_train_encoded['SalePrice']

In [29]:
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor

from genetic_selection import GeneticSelectionCV
estimator = linear_model.LinearRegression()

selector = GeneticSelectionCV(estimator,cv=5,
                                  verbose=1,
                                  scoring="r2",
                                  max_features=10,
                                  n_population=400,
                                  crossover_proba=0.5,
                                  mutation_proba=0.2,
                                  n_generations=40,
                                  crossover_independent_proba=0.5,
                                  mutation_independent_proba=0.05,
                                  tournament_size=3,
                                  n_gen_no_change=10,
                                  caching=True,
                                  n_jobs=-1)
selector = selector.fit(x_train, y_train)

print(selector.support_)

Selecting features with genetic algorithm.
gen	nevals	avg                      	std                  	min              	max
0  	400   	[-10000.         30.3325]	[0.        3.7130774]	[-10000.     20.]	[-10000.     41.]
1  	241   	[-10000.       27.39]    	[0.         3.09481825]	[-10000.     20.]	[-10000.     37.]
2  	221   	[-10000.         25.0025]	[0.         2.80223014]	[-10000.     16.]	[-10000.     34.]
3  	233   	[-10000.         22.8025]	[0.         2.84402773]	[-10000.     15.]	[-10000.     33.]
4  	224   	[-10000.        20.835]  	[0.         2.68845216]	[-10000.     14.]	[-10000.     33.]
5  	264   	[-10000.       18.83]    	[0.         2.55070578]	[-10000.     12.]	[-10000.     27.]
6  	232   	[-10000.       17.03]    	[0.         2.33004292]	[-10000.     11.]	[-10000.     25.]
7  	244   	[-9824.99199449    15.2675    ]	[1311.30938866    2.6049844 ]	[-1.e+04  6.e+00]	[ 0.69765728 25.        ]
8  	256   	[-9199.95689636    13.6775    ]	[2.71307817e+03 2.49869841e+00]	[-1.e+04  6.e+00]	[ 0.82925797 24.        ]
9  	245   	[-7049.84028716    11.9425    ]	[4.56067451e+03 2.54837080e+00]	[-1.e+04  6.e+00]	[ 0.82660895 23.        ]
10 	267   	[-4549.69124653    10.4975    ]	[4.97999094e+03 2.37802308e+00]	[-1.e+04  4.e+00]	[ 0.83728389 18.        ]
11 	225   	[-2524.53947016     9.57      ]	[4.34473253e+03 1.97360077e+00]	[-1.e+04  4.e+00]	[ 0.83728389 17.        ]
12 	223   	[-1624.43143597     9.15      ]	[3.68933909e+03 1.85404962e+00]	[-1.e+04  5.e+00]	[ 0.83728389 18.        ]
13 	241   	[-2024.41750044     9.355     ]	[4.01892202e+03 2.05035972e+00]	[-1.e+04  2.e+00]	[ 0.84423601 19.        ]
14 	237   	[-2274.41397753     9.395     ]	[4.19249824e+03 1.97331574e+00]	[-1.e+04  4.e+00]	[ 0.85589647 18.        ]
15 	245   	[-2049.37811871     9.19      ]	[4.03733202e+03 2.05399611e+00]	[-1.e+04  3.e+00]	[ 0.86145291 15.        ]
16 	253   	[-2199.3701457     9.355    ]  	[4.14279754e+03 1.87589312e+00]	[-1.e+04  5.e+00]	[ 0.8610076 17.       ]
17 	237   	[-1699.31858613     9.1525    ]	[3.75663638e+03 1.75477741e+00]	[-1.e+04  4.e+00]	[ 0.86240348 14.        ]
18 	232   	[-2424.36979434     9.405     ]	[4.28630746e+03 1.98014520e+00]	[-1.e+04  4.e+00]	[ 0.87403216 16.        ]
19 	256   	[-1924.32017774     9.255     ]	[3.94296746e+03 1.88015292e+00]	[-1.e+04  4.e+00]	[ 0.87438335 17.        ]
20 	253   	[-2049.32353999     9.37      ]	[4.03735973e+03 1.70531522e+00]	[-1.e+04  5.e+00]	[ 0.88063934 15.        ]
21 	221   	[-1824.30041769     9.42      ]	[3.86289122e+03 1.64578249e+00]	[-1.e+04  5.e+00]	[ 0.88063934 17.        ]
22 	212   	[-1624.27814865     9.4725    ]	[3.68940661e+03 1.63071878e+00]	[-1.e+04  5.e+00]	[ 0.88237379 17.        ]
23 	244   	[-2124.31792713     9.6525    ]	[4.09112135e+03 1.64065345e+00]	[-1.e+04  5.e+00]	[ 0.88621209 16.        ]
24 	222   	[-1999.30586958     9.68      ]	[4.00034707e+03 1.53381876e+00]	[-1.e+04  6.e+00]	[ 0.88405071 17.        ]
25 	233   	[-2099.31027663     9.81      ]	[4.07343798e+03 1.66099368e+00]	[-1.e+04  6.e+00]	[ 0.88680538 16.        ]
26 	247   	[-2299.32578461     9.835     ]	[4.20869357e+03 1.49424730e+00]	[-1.e+04  7.e+00]	[ 0.88883729 17.        ]
27 	234   	[-1974.29581058     9.825     ]	[3.98147669e+03 1.42280533e+00]	[-1.e+04  6.e+00]	[ 0.88883729 17.        ]
28 	237   	[-2199.31432353     9.9925    ]	[4.14282719e+03 1.49246231e+00]	[-1.e+04  6.e+00]	[ 0.88883729 19.        ]
29 	250   	[-2274.31972017    10.0975    ]	[4.19254939e+03 1.33715883e+00]	[-1.e+04  6.e+00]	[ 0.88883729 16.        ]
30 	231   	[-2324.32215559    10.1825    ]	[4.22463337e+03 1.30927222e+00]	[-1.e+04  8.e+00]	[ 0.88883729 16.        ]
31 	235   	[-2349.3237953    10.2025   ]  	[4.24036299e+03 1.27925515e+00]	[-1.e+04  8.e+00]	[ 0.88883729 18.        ]
32 	266   	[-2749.3584837    10.38     ]  	[4.46553787e+03 1.47329563e+00]	[-1.e+04  8.e+00]	[ 0.88883729 16.        ]
33 	245   	[-2424.32904414    10.285     ]	[4.28633051e+03 1.15055421e+00]	[-1.e+04  8.e+00]	[ 0.88883729 16.        ]
34 	239   	[-2324.31951874    10.3725    ]	[4.22463482e+03 1.19111030e+00]	[-1.e+04  8.e+00]	[ 0.88883729 16.        ]
35 	234   	[-1749.26795879    10.3125    ]	[3.80000819e+03 1.08159315e+00]	[-1.e+04  8.e+00]	[ 0.88883729 17.        ]
36 	254   	[-1824.27395824    10.4675    ]	[3.86290372e+03 1.32436541e+00]	[-1.e+04  9.e+00]	[ 0.88883729 18.        ]
[False False False  True False False False False False False False False
 False False False  True  True  True False False False False False False
 False False  True False False  True False  True False False False False
  True False False False False False  True False False False False  True
 False False False False False False False False False False False False
 False]